/**
 * Rollup 配置文件
 * 将模块化的代码打包成单文件 IIFE
 */

import resolve from '@rollup/plugin-node-resolve';
import terser from '@rollup/plugin-terser';
import replace from '@rollup/plugin-replace';

const production = process.env.NODE_ENV === 'production';

export default {
  input: 'src/inject-refactored.js',
  output: {
    file: 'src/inject.js',
    format: 'iife',
    name: 'TauriInject',
    sourcemap: !production, // 生产环境不生成 sourcemap
    banner: '// Backstage68 Inject Script - Generated from modular source\n// DO NOT EDIT THIS FILE DIRECTLY - Edit src/inject-refactored.js and run npm run build\n',
    globals: {
      'process': 'undefined'
    }
  },
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify(production ? 'production' : 'development'),
      preventAssignment: true
    }),
    resolve({
      browser: true, // 使用浏览器版本的包
      preferBuiltins: false
    }),
    production && terser({
      compress: {
        drop_console: false, // 保留 console，因为有日志控制
        pure_funcs: [] // 不删除任何函数
      },
      format: {
        comments: false // 删除注释
      }
    })
  ]
};

