// Backstage68 Inject Script - Generated from modular source
// DO NOT EDIT THIS FILE DIRECTLY - Edit src/inject-refactored.js and run npm run build

(function () {
  'use strict';

  /**
   * 日志工具模块
   */

  function initLogger() {
    const ENABLE_LOGS = window.__TAURI_ENABLE_LOGS__ || false;
    
    const log = (...args) => {
      if (ENABLE_LOGS) {
        console.log(...args);
      }
    };
    
    log.info = (...args) => {
      if (ENABLE_LOGS) {
        console.info(...args);
      }
    };
    
    log.warn = (...args) => {
      if (ENABLE_LOGS) {
        console.warn(...args);
      }
    };
    
    log.error = (...args) => {
      console.error(...args); // 错误始终输出
    };
    
    return log;
  }

  /**
   * DOM 工具模块
   */

  /**
   * 检查是否在 iframe 内
   */
  function isInIframe() {
    return window.self !== window.top;
  }

  /**
   * 检查是否为 Mac
   */
  function isMac() {
    return navigator.platform.toUpperCase().indexOf('MAC') >= 0;
  }

  /**
   * 获取修饰键（Mac: metaKey, Windows: ctrlKey）
   */
  function getModifierKey(event) {
    return isMac() ? event.metaKey : event.ctrlKey;
  }

  /**
   * HTTP 代理拦截模块 (Fetch + XMLHttpRequest)
   */

  function initProxy(log, invoke) {
    log("🚀 初始化代理模块...");
    
    // --- Override window.fetch ---
    const originalFetch = window.fetch;
    
    window.fetch = async function(input, init) {
      let url = input;
      if (input instanceof Request) {
        url = input.url;
        if (!init) {
          init = {
            method: input.method,
            headers: input.headers,
            body: input.body
          };
        }
      }
      
      if (url.startsWith('/')) {
        url = window.location.origin + url;
      }

      if (url.includes('ipc://localhost') || url.includes('tauri://')) {
        return originalFetch.apply(this, arguments);
      }

      if (!url.includes('/base_api/')) {
        return originalFetch.apply(this, arguments);
      }

      log("🔄 [Fetch] Intercepted:", url);

      let headers = {};
      if (init && init.headers) {
        if (init.headers instanceof Headers) {
          init.headers.forEach((v, k) => headers[k] = v);
        } else {
          headers = init.headers;
        }
      }

      let body = null;
      let formData = null;
      let files = null;
      
      if (init && init.body) {
        if (typeof init.body === 'string') {
          body = init.body;
        } else if (init.body instanceof FormData) {
          log("📦 检测到 FormData");
          formData = [];
          files = [];
          
          for (const [key, value] of init.body.entries()) {
            if (value instanceof File) {
              const reader = new FileReader();
              const filePromise = new Promise((resolve) => {
                reader.onload = () => {
                  const base64 = reader.result.split(',')[1];
                  files.push({
                    field_name: key,
                    file_name: value.name,
                    content_type: value.type || 'application/octet-stream',
                    data: base64
                  });
                  resolve();
                };
                reader.onerror = () => resolve();
              });
              reader.readAsDataURL(value);
              await filePromise;
            } else {
              formData.push([key, value.toString()]);
            }
          }
          
          delete headers['Content-Type'];
          delete headers['content-type'];
        } else {
          try {
            body = JSON.stringify(init.body);
          } catch(e) {
            log.warn("Could not stringify body", e);
          }
        }
      }

      const reqData = {
        method: (init && init.method) ? init.method.toUpperCase() : 'GET',
        url: url.toString(),
        headers: headers,
        body: body,
        form_data: formData,
        files: files && files.length > 0 ? files : null
      };

      try {
        const response = await invoke('proxy_request', { request: reqData });
        
        if (response.status === 403) {
          log.error("⚠️ 403 Forbidden!");
        }
        
        return new Response(response.body, {
          status: response.status,
          statusText: response.status === 200 ? 'OK' : 'Error',
          headers: new Headers(response.headers)
        });
        
      } catch (err) {
        log.error("❌ Proxy Request Failed:", err);
        throw err;
      }
    };

    // --- Override XMLHttpRequest ---
    const OriginalXHR = window.XMLHttpRequest;
    
    function ProxyXHR() {
      this.headers = {};
      this.responseHeaders = {};
      this.onreadystatechange = null;
      this.onload = null;
      this.onerror = null;
      this.status = 0;
      this.readyState = 0;
      this.responseText = "";
      this.response = "";
    }

    ProxyXHR.prototype.open = function(method, url, async, user, password) {
      this.method = method;
      this.url = url;
      this.readyState = 1;
      if (this.onreadystatechange) this.onreadystatechange();
    };

    ProxyXHR.prototype.setRequestHeader = function(header, value) {
      this.headers[header] = value;
    };

    ProxyXHR.prototype.send = function(data) {
      let url = this.url;
      if (url.startsWith('/')) {
        url = window.location.origin + url;
      }
      
      if (!url.includes('/base_api/')) {
        const originalXHR = new OriginalXHR();
        originalXHR.open(this.method, this.url, true);
        for (const [key, value] of Object.entries(this.headers)) {
          originalXHR.setRequestHeader(key, value);
        }
        originalXHR.onload = () => {
          this.status = originalXHR.status;
          this.responseText = originalXHR.responseText;
          this.response = originalXHR.response;
          this.readyState = 4;
          if (this.onreadystatechange) this.onreadystatechange();
          if (this.onload) this.onload();
        };
        originalXHR.onerror = (err) => {
          if (this.onerror) this.onerror(err);
        };
        originalXHR.send(data);
        return;
      }
      
      const self = this;
      
      if (data instanceof FormData) {
        (async () => {
          try {
            const formDataArray = [];
            const filesArray = [];
            
            for (const [key, value] of data.entries()) {
              if (value instanceof File) {
                const base64 = await new Promise((resolve, reject) => {
                  const reader = new FileReader();
                  reader.onload = () => resolve(reader.result.split(',')[1]);
                  reader.onerror = () => reject(reader.error);
                  reader.readAsDataURL(value);
                });
                
                filesArray.push({
                  field_name: key,
                  file_name: value.name,
                  content_type: value.type || 'application/octet-stream',
                  data: base64
                });
              } else {
                formDataArray.push([key, value.toString()]);
              }
            }
            
            const reqData = {
              method: self.method,
              url: url,
              headers: self.headers,
              body: null,
              form_data: formDataArray.length > 0 ? formDataArray : null,
              files: filesArray.length > 0 ? filesArray : null
            };
            
            delete reqData.headers['Content-Type'];
            delete reqData.headers['content-type'];
            
            const response = await invoke('proxy_request', { request: reqData });
            
            self.status = response.status;
            self.statusText = response.status === 200 ? "OK" : "";
            self.responseText = response.body;
            self.response = response.body;
            self.readyState = 4;
            self.responseHeaders = response.headers;
            
            if (self.onreadystatechange) self.onreadystatechange();
            if (self.onload) self.onload();
            
          } catch (err) {
            log.error("XHR FormData Error:", err);
            if (self.onerror) self.onerror(err);
          }
        })();
        return;
      }
      
      const reqData = {
        method: this.method,
        url: url,
        headers: this.headers,
        body: data ? data.toString() : null
      };
      
      invoke('proxy_request', { request: reqData })
        .then(response => {
          self.status = response.status;
          self.statusText = response.status === 200 ? "OK" : "";
          self.responseText = response.body;
          self.response = response.body;
          self.readyState = 4;
          self.responseHeaders = response.headers;

          if (self.onreadystatechange) self.onreadystatechange();
          if (self.onload) self.onload();
        })
        .catch(err => {
          log.error("XHR Proxy Error", err);
          if (self.onerror) self.onerror(err);
        });
    };
    
    ProxyXHR.prototype.getAllResponseHeaders = function() {
      let res = "";
      for (const [k, v] of Object.entries(this.responseHeaders)) {
        res += `${k}: ${v}\r\n`;
      }
      return res;
    };
    
    ProxyXHR.prototype.getResponseHeader = function(name) {
      return this.responseHeaders[name] || null;
    };

    window.XMLHttpRequest = ProxyXHR;
    log("✅ 代理模块已启用");
  }

  /**
   * 页面缩放模块
   */


  const MIN_ZOOM = 0.25;   // 25%
  const MAX_ZOOM = 5.0;    // 500%
  const ZOOM_STEP = 0.05;  // 5%

  function initZoom(log) {
    log("🔍 初始化缩放模块...");
    
    let currentZoom = 1.0;
    let zoomIndicator = null;
    let zoomTimeout = null;

    function createZoomIndicator() {
      if (!zoomIndicator) {
        zoomIndicator = document.createElement('div');
        zoomIndicator.style.cssText = `
        position: fixed;
        top: 20px;
        right: 20px;
        background: rgba(0, 0, 0, 0.6);
        color: white;
        padding: 12px 24px;
        border-radius: 8px;
        font-size: 24px;
        font-weight: bold;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        z-index: 999999;
        pointer-events: none;
        opacity: 0;
        transition: opacity 0.2s ease;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
      `;
        document.body.appendChild(zoomIndicator);
      }
      return zoomIndicator;
    }

    function showZoomIndicator(zoom) {
      const indicator = createZoomIndicator();
      indicator.textContent = `${Math.round(zoom * 100)}%`;
      indicator.style.opacity = '1';

      if (zoomTimeout) {
        clearTimeout(zoomTimeout);
      }

      zoomTimeout = setTimeout(() => {
        indicator.style.opacity = '0';
      }, 1000);
    }

    async function applyZoom(zoom) {
      try {
        currentZoom = zoom;
        if (window.tauriTabs) {
          window.tauriTabs.currentZoom = zoom;
        }
        showZoomIndicator(zoom);
        
        if (window.self === window.top && window.tauriTabs && window.tauriTabs.activeTabId) {
          const activeTab = window.tauriTabs.tabs.find(t => t.id === window.tauriTabs.activeTabId);
          if (activeTab && activeTab.iframe) {
            try {
              const iframeDoc = activeTab.iframe.contentDocument || activeTab.iframe.contentWindow.document;
              if (iframeDoc && iframeDoc.body) {
                iframeDoc.body.style.zoom = zoom;
                return;
              }
            } catch (e) {
              // Ignore
            }
          }
        }
        
        if (document.body) {
          document.body.style.zoom = zoom;
        }
      } catch (err) {
        log.error("缩放失败:", err);
      }
    }

    async function zoomIn() {
      const newZoom = Math.min(currentZoom + ZOOM_STEP, MAX_ZOOM);
      await applyZoom(newZoom);
    }

    async function zoomOut() {
      const newZoom = Math.max(currentZoom - ZOOM_STEP, MIN_ZOOM);
      await applyZoom(newZoom);
    }

    async function zoomReset() {
      await applyZoom(1.0);
    }

    // 键盘快捷键
    document.addEventListener('keydown', async (e) => {
      const ctrlKey = getModifierKey(e);

      if (ctrlKey && (e.key === '+' || e.key === '=')) {
        e.preventDefault();
        if (window.self !== window.top && window.parent.tauriZoom) {
          await window.parent.tauriZoom.zoomIn();
        } else {
          await zoomIn();
        }
      } else if (ctrlKey && e.key === '-') {
        e.preventDefault();
        if (window.self !== window.top && window.parent.tauriZoom) {
          await window.parent.tauriZoom.zoomOut();
        } else {
          await zoomOut();
        }
      } else if (ctrlKey && e.key === '0') {
        e.preventDefault();
        if (window.self !== window.top && window.parent.tauriZoom) {
          await window.parent.tauriZoom.reset();
        } else {
          await zoomReset();
        }
      }
    });

    // 鼠标滚轮缩放
    document.addEventListener('wheel', async (e) => {
      const ctrlKey = getModifierKey(e);

      if (ctrlKey) {
        e.preventDefault();
        
        if (window.self !== window.top && window.parent.tauriZoom) {
          if (e.deltaY < 0) {
            await window.parent.tauriZoom.zoomIn();
          } else {
            await window.parent.tauriZoom.zoomOut();
          }
        } else {
          if (e.deltaY < 0) {
            await zoomIn();
          } else {
            await zoomOut();
          }
        }
      }
    }, { passive: false });

    // 暴露到全局
    window.tauriZoom = {
      zoomIn,
      zoomOut,
      reset: zoomReset,
      get: () => currentZoom,
      set: applyZoom
    };

    log("✅ 缩放模块已启用");
  }

  /**
   * 存储工具模块
   */

  /**
   * 序列化存储数据（用于跨窗口传递）
   */
  function serializeStorage() {
    const data = {
      localStorage: {},
      sessionStorage: {}
    };
    
    // 复制 localStorage
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      data.localStorage[key] = localStorage.getItem(key);
    }
    
    // 复制 sessionStorage
    for (let i = 0; i < sessionStorage.length; i++) {
      const key = sessionStorage.key(i);
      data.sessionStorage[key] = sessionStorage.getItem(key);
    }
    
    return data;
  }

  /**
   * 多窗口支持模块
   */


  function initWindow(log, invoke) {
    log("🪟 初始化多窗口模块...");

    // 创建新窗口（打开当前页面，并复制登录状态）
    window.tauriOpenNewWindow = async function(url) {
      try {
        const targetUrl = url || window.location.href;
        log(`🪟 准备打开新窗口: ${targetUrl}`);
        
        const storageData = serializeStorage();
        
        const windowLabel = await invoke('create_new_window', { 
          currentUrl: targetUrl,
          storageData: JSON.stringify(storageData)
        });
        
        log(`✅ 新窗口已创建: ${windowLabel}`);
        return windowLabel;
      } catch (err) {
        console.error("❌ 创建窗口失败:", err);
        throw err;
      }
    };

    // 快捷键：Cmd/Ctrl+Shift+N 创建新窗口（打开当前页面）
    document.addEventListener('keydown', (e) => {
      if (getModifierKey(e) && e.shiftKey && e.key === 'n') {
        e.preventDefault();
        e.stopPropagation();
        log('🔥 Cmd+Shift+N 触发，打开新窗口');
        window.tauriOpenNewWindow();
      }
    }, true);

    // 窗口标题同步
    initWindowTitleSync(log, invoke);

    log("✅ 多窗口模块已启用");
  }

  // 窗口标题同步（跟随页面标题变化）
  function initWindowTitleSync(log, invoke) {
    let envName = 'Backstage68';
    
    // 异步获取环境名称
    (async function() {
      try {
        const envInfo = await invoke('get_env_info');
        const match = envInfo.match(/当前环境: (.+?) \(/);
        if (match) {
          envName = match[1];
          log(`✅ 环境名称: ${envName}`);
        }
      } catch (err) {
        log('⚠️ 无法获取环境名称，使用默认值');
      }
    })();
    
    // 更新窗口标题的函数
    async function updateWindowTitle() {
      try {
        const pageTitle = document.title || '未命名页面';
        const newTitle = `${pageTitle} - ${envName}`;
        
        await invoke('set_window_title', { title: newTitle });
        log(`✅ 窗口标题已更新: ${newTitle}`);
      } catch (err) {
        console.error('❌ 更新窗口标题失败:', err);
      }
    }
    
    // 监听 document.title 变化
    const titleObserver = new MutationObserver(() => {
      log('🔔 检测到标题变化:', document.title);
      updateWindowTitle();
    });
    
    const titleElement = document.querySelector('title');
    if (titleElement) {
      titleObserver.observe(titleElement, {
        childList: true,
        subtree: true,
        characterData: true
      });
      log('👀 开始监听页面标题变化');
    }
    
    // 初始化时更新一次标题
    if (document.readyState === 'complete') {
      setTimeout(updateWindowTitle, 500);
    } else {
      window.addEventListener('load', () => {
        setTimeout(updateWindowTitle, 500);
      });
    }
    
    // 路由变化时也更新标题（适配 SPA）
    let lastUrl = window.location.href;
    setInterval(() => {
      const currentUrl = window.location.href;
      if (currentUrl !== lastUrl) {
        lastUrl = currentUrl;
        log('🔄 路由变化，等待标题更新...');
        setTimeout(updateWindowTitle, 300);
      }
    }, 500);
  }

  /**
   * 标签页 UI 模块
   */

  const TAB_CONFIG = {
    maxTabs: 20,
    tabBarHeight: 40,
    minTabWidth: 40,
    maxTabWidth: 200,
    defaultTabWidth: 200
  };

  // 创建标签栏
  function createTabBar() {
    const tabBar = document.createElement('div');
    tabBar.id = 'tauri-tab-bar';
    tabBar.style.cssText = `
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    height: ${TAB_CONFIG.tabBarHeight}px;
    background: linear-gradient(180deg, #3a3a3a 0%, #2c2c2c 100%);
    display: flex;
    align-items: center;
    padding: 0;
    z-index: 999999;
    user-select: none;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    box-shadow: 0 2px 8px rgba(0,0,0,0.3);
  `;
    
    const tabsContainer = document.createElement('div');
    tabsContainer.className = 'tauri-tabs-container';
    tabsContainer.style.cssText = `
    flex: 1;
    display: flex;
    align-items: center;
    padding: 0 8px;
    overflow: hidden;
    gap: 4px;
  `;
    
    const controlsContainer = document.createElement('div');
    controlsContainer.className = 'tauri-tab-controls-fixed';
    controlsContainer.style.cssText = `
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 0 8px;
    flex-shrink: 0;
    background: linear-gradient(90deg, rgba(42, 42, 42, 0.8) 0%, #2c2c2c 20%);
  `;
    
    tabBar.appendChild(tabsContainer);
    tabBar.appendChild(controlsContainer);
    
    createStyles();
    document.body.appendChild(tabBar);
    
    return { tabBar, tabsContainer, controlsContainer };
  }

  // 创建样式
  function createStyles() {
    const style = document.createElement('style');
    style.textContent = `
    .tauri-tabs-container::-webkit-scrollbar { display: none; }
    .tauri-tab {
      min-width: ${TAB_CONFIG.minTabWidth}px;
      max-width: ${TAB_CONFIG.maxTabWidth}px;
      width: ${TAB_CONFIG.defaultTabWidth}px;
      height: 30px;
      background: rgba(255,255,255,0.05);
      border-radius: 6px 6px 0 0;
      display: flex;
      align-items: center;
      padding: 0 8px;
      cursor: pointer;
      transition: background 0.2s, width 0.3s ease;
      flex-shrink: 1;
      position: relative;
    }
    .tauri-tab:hover { background: rgba(255,255,255,0.1); }
    .tauri-tab.active {
      background: rgba(255,255,255,0.15);
      box-shadow: 0 -2px 0 0 #0066cc inset;
    }
    .tauri-tab-title {
      flex: 1;
      color: #e0e0e0;
      font-size: 13px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .tauri-tab.active .tauri-tab-title { color: #ffffff; }
    .tauri-tab-close {
      margin-left: 8px;
      color: #999;
      font-size: 18px;
      line-height: 1;
      width: 16px;
      height: 16px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 3px;
      flex-shrink: 0;
    }
    .tauri-tab-close:hover {
      background: rgba(255,255,255,0.2);
      color: #fff;
    }
    .tauri-new-tab, .tauri-search-tab {
      min-width: 32px;
      width: 32px;
      height: 30px;
      background: rgba(255,255,255,0.05);
      border-radius: 6px;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      transition: background 0.2s;
      color: #e0e0e0;
      flex-shrink: 0;
    }
    .tauri-new-tab { font-size: 20px; }
    .tauri-search-tab { font-size: 18px; }
    .tauri-new-tab:hover, .tauri-search-tab:hover {
      background: rgba(255,255,255,0.15);
    }
    .tauri-iframe-container {
      position: fixed;
      top: ${TAB_CONFIG.tabBarHeight}px;
      left: 0;
      right: 0;
      bottom: 0;
      width: 100%;
      height: calc(100vh - ${TAB_CONFIG.tabBarHeight}px);
    }
    .tauri-tab-iframe {
      width: 100%;
      height: 100%;
      border: none;
      display: none;
    }
    .tauri-tab-iframe.active { display: block; }
    .tauri-tab.dragging {
      opacity: 0.5;
      cursor: grabbing;
    }
    .tauri-tab.drag-over {
      background: rgba(255,255,255,0.25);
      border-left: 2px solid #0066cc;
    }
  `;
    document.head.appendChild(style);
  }

  // 更新标签宽度（自适应）
  function updateTabWidths() {
    const container = document.querySelector('.tauri-tabs-container');
    if (!container) return;
    
    const newTabBtn = container.querySelector('.tauri-new-tab');
    const tabs = Array.from(container.querySelectorAll('.tauri-tab'));
    
    if (tabs.length === 0) return;
    
    const containerWidth = container.clientWidth;
    const newTabBtnWidth = newTabBtn ? 36 : 0;
    const gap = 4;
    const padding = 16;
    
    const availableWidth = containerWidth - newTabBtnWidth - padding - (gap * tabs.length);
    const idealWidth = availableWidth / tabs.length;
    
    const finalWidth = Math.max(
      TAB_CONFIG.minTabWidth,
      Math.min(TAB_CONFIG.maxTabWidth, idealWidth)
    );
    
    tabs.forEach(tab => {
      tab.style.width = `${finalWidth}px`;
    });
  }

  /**
   * 标签页操作模块 - CRUD 操作
   */


  // 创建标签 DOM 元素
  function createTabElement(id, title, callbacks) {
    const { onClose, onSwitch, onContextMenu, onDragEvents } = callbacks;
    
    const tab = document.createElement('div');
    tab.className = 'tauri-tab';
    tab.dataset.tabId = id;
    tab.setAttribute('draggable', 'true');
    
    const titleSpan = document.createElement('span');
    titleSpan.className = 'tauri-tab-title';
    titleSpan.textContent = title;
    tab.appendChild(titleSpan);
    
    if (TAB_CONFIG.enableCloseButton) {
      const closeBtn = document.createElement('span');
      closeBtn.className = 'tauri-tab-close';
      closeBtn.innerHTML = '×';
      closeBtn.title = '关闭标签 (Cmd+W)';
      closeBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        onClose(id);
      });
      tab.appendChild(closeBtn);
    }
    
    tab.addEventListener('click', () => onSwitch(id));
    tab.addEventListener('contextmenu', (e) => {
      e.preventDefault();
      e.stopPropagation();
      onContextMenu(id, e.clientX, e.clientY);
    });
    
    // 拖动事件
    if (onDragEvents) {
      tab.addEventListener('dragstart', (e) => onDragEvents.dragStart(e, id, tab));
      tab.addEventListener('dragend', (e) => onDragEvents.dragEnd(e, id, tab));
      tab.addEventListener('dragover', (e) => onDragEvents.dragOver(e, tab));
      tab.addEventListener('dragleave', (e) => onDragEvents.dragLeave(e, tab));
      tab.addEventListener('drop', (e) => onDragEvents.drop(e, id, tab));
    }
    
    return tab;
  }

  // 创建 iframe 容器
  function createIframeContainer() {
    const container = document.createElement('div');
    container.className = 'tauri-iframe-container';
    document.body.appendChild(container);
    return container;
  }

  // 创建 iframe
  function createIframe(url, log) {
    const container = document.querySelector('.tauri-iframe-container') || createIframeContainer();
    
    const iframe = document.createElement('iframe');
    iframe.className = 'tauri-tab-iframe';
    iframe.src = url;
    
    container.appendChild(iframe);
    
    // iframe 加载完成后，设置代理和事件监听
    iframe.addEventListener('load', () => {
      try {
        const iframeWindow = iframe.contentWindow;
        const iframeDoc = iframe.contentDocument;
        
        if (iframeWindow && iframeDoc && window.self === window.top) {
          // 用父窗口的代理替换 iframe 的 fetch 和 XHR
          iframeWindow.fetch = window.fetch;
          iframeWindow.XMLHttpRequest = window.XMLHttpRequest;
          log(`✅ iframe 已继承父窗口的代理`);
          
          // 在 iframe 内部添加键盘事件监听器
          setupIframeEvents(iframeDoc, log);
          
          log(`✅ iframe 事件监听器已安装`);
        }
      } catch (err) {
        log(`⚠️  无法设置 iframe: ${err.message}`);
      }
    });
    
    return iframe;
  }

  // 设置 iframe 内部事件
  function setupIframeEvents(iframeDoc, log) {
    const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
    
    // 键盘事件
    iframeDoc.addEventListener('keydown', (e) => {
      const isCtrlOrCmd = isMac ? e.metaKey : e.ctrlKey;
      
      if (!isCtrlOrCmd) return;
      
      // 缩放快捷键
      if (e.key === '+' || e.key === '=') {
        e.preventDefault();
        if (window.tauriZoom && window.tauriZoom.zoomIn) {
          window.tauriZoom.zoomIn();
        }
      } else if (e.key === '-') {
        e.preventDefault();
        if (window.tauriZoom && window.tauriZoom.zoomOut) {
          window.tauriZoom.zoomOut();
        }
      } else if (e.key === '0') {
        e.preventDefault();
        if (window.tauriZoom && window.tauriZoom.reset) {
          window.tauriZoom.reset();
        }
      }
      
      // 标签页快捷键
      if (window.tauriTabs && window.tauriTabs.tabs) {
        if (e.key === 't') {
          e.preventDefault();
          const activeTab = window.tauriTabs.tabs.find(t => t.id === window.tauriTabs.activeTabId);
          const currentUrl = activeTab ? activeTab.url : window.location.href;
          if (window.tauriTabs.createTab) {
            window.tauriTabs.createTab(currentUrl);
          }
        } else if (e.key === 'w' && window.tauriTabs.tabs.length > 1) {
          e.preventDefault();
          if (window.tauriTabs.activeTabId && window.tauriTabs.closeTab) {
            window.tauriTabs.closeTab(window.tauriTabs.activeTabId);
          }
        } else if (e.key >= '1' && e.key <= '9') {
          e.preventDefault();
          const index = parseInt(e.key) - 1;
          if (index < window.tauriTabs.tabs.length && window.tauriTabs.activateTab) {
            window.tauriTabs.activateTab(window.tauriTabs.tabs[index].id);
          }
        }
      }
    }, true);
    
    // 鼠标滚轮缩放
    iframeDoc.addEventListener('wheel', (e) => {
      const isCtrlOrCmd = isMac ? e.metaKey : e.ctrlKey;
      
      if (isCtrlOrCmd) {
        e.preventDefault();
        if (e.deltaY < 0) {
          if (window.tauriZoom && window.tauriZoom.zoomIn) {
            window.tauriZoom.zoomIn();
          }
        } else {
          if (window.tauriZoom && window.tauriZoom.zoomOut) {
            window.tauriZoom.zoomOut();
          }
        }
      }
    }, { passive: false, capture: true });
  }

  // 创建新标签
  function createTab(url) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    
    if (tabs.length >= TAB_CONFIG.maxTabs) {
      alert(`最多只能打开 ${TAB_CONFIG.maxTabs} 个标签`);
      return;
    }
    
    const id = 'tab-' + (++window.tauriTabs.nextId);
    const title = '加载中...';
    
    log(`📑 创建新标签: ${id}, URL: ${url}`);
    
    const tabElement = createTabElement(id, title, {
      onClose: closeTab,
      onSwitch: activateTab,
      onContextMenu: window.tauriTabs.showContextMenu || (() => {}),
      onDragEvents: window.tauriTabs.dragEvents || null
    });
    
    const iframe = createIframe(url, log);
    
    const tabsContainer = document.querySelector('.tauri-tabs-container');
    const newTabBtn = tabsContainer.querySelector('.tauri-new-tab');
    tabsContainer.insertBefore(tabElement, newTabBtn);
    
    const tabData = {
      id,
      url,
      title,
      element: tabElement,
      iframe
    };
    
    tabs.push(tabData);
    
    // 监听 iframe 标题变化
    setupTitleObserver(iframe, id, tabData, log);
    
    activateTab(id);
    updateTabWidths();
    
    return id;
  }

  // 设置标题观察器
  function setupTitleObserver(iframe, id, tabData, log) {
    iframe.addEventListener('load', () => {
      try {
        const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
        const newTitle = iframeDoc.title || tabData.url;
        updateTabTitle(id, newTitle);
        
        log(`📄 iframe 加载完成，标题: ${newTitle}`);
        
        // 监听标题变化
        const titleElement = iframeDoc.querySelector('title');
        if (titleElement) {
          const observer = new MutationObserver(() => {
            const updatedTitle = iframeDoc.title;
            if (updatedTitle && updatedTitle !== tabData.title) {
              log(`📝 检测到标题变化: ${updatedTitle}`);
              updateTabTitle(id, updatedTitle);
            }
          });
          observer.observe(titleElement, { 
            subtree: true, 
            characterData: true, 
            childList: true 
          });
          tabData.titleObserver = observer;
        }
        
        // 定期检查标题（兜底）
        const titleCheckInterval = setInterval(() => {
          try {
            const currentTitle = iframeDoc.title;
            if (currentTitle && currentTitle !== tabData.title) {
              log(`🔄 定期检查发现标题变化: ${currentTitle}`);
              updateTabTitle(id, currentTitle);
            }
          } catch (err) {
            clearInterval(titleCheckInterval);
          }
        }, 1000);
        tabData.titleCheckInterval = titleCheckInterval;
        
        // 应用当前缩放
        const zoomLevel = window.tauriTabs.currentZoom || 1.0;
        if (zoomLevel !== 1.0 && iframeDoc.body) {
          iframeDoc.body.style.zoom = zoomLevel;
          log(`🔍 应用缩放 ${Math.round(zoomLevel * 100)}% 到新标签`);
        }
      } catch (e) {
        updateTabTitle(id, tabData.url);
        log(`⚠️  无法访问 iframe 内容 (可能跨域)`);
      }
    });
  }

  // 激活标签
  function activateTab(id) {
    const tabs = window.tauriTabs.tabs;
    const tab = tabs.find(t => t.id === id);
    const log = window.tauriTabs.log;
    
    if (!tab) return;
    
    log(`🔄 切换到标签: ${id}`);
    
    tabs.forEach(t => {
      if (t.id === id) {
        t.element.classList.add('active');
        t.iframe.classList.add('active');
      } else {
        t.element.classList.remove('active');
        t.iframe.classList.remove('active');
      }
    });
    
    window.tauriTabs.activeTabId = id;
    
    // 更新窗口标题
    if (tab.title) {
      updateMainWindowTitle(tab.title);
    }
    
    // 应用缩放
    const zoomLevel = window.tauriTabs.currentZoom || 1.0;
    if (zoomLevel !== 1.0) {
      setTimeout(() => {
        try {
          const iframeDoc = tab.iframe.contentDocument || tab.iframe.contentWindow.document;
          if (iframeDoc && iframeDoc.body) {
            iframeDoc.body.style.zoom = zoomLevel;
            log(`🔍 切换标签后应用缩放: ${Math.round(zoomLevel * 100)}%`);
          }
        } catch (e) {
          log(`⚠️  无法应用缩放到 iframe: ${e.message}`);
        }
      }, 100);
    }
  }

  // 关闭标签
  function closeTab(id) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    const index = tabs.findIndex(t => t.id === id);
    
    if (index === -1) return;
    
    if (tabs.length === 1) {
      log('⚠️  不能关闭最后一个标签');
      return;
    }
    
    log(`❌ 关闭标签: ${id}`);
    
    const tab = tabs[index];
    
    // 清理观察器和定时器
    if (tab.titleObserver) {
      tab.titleObserver.disconnect();
    }
    if (tab.titleCheckInterval) {
      clearInterval(tab.titleCheckInterval);
    }
    
    tab.element.remove();
    tab.iframe.remove();
    tabs.splice(index, 1);
    
    // 切换到相邻标签
    if (id === window.tauriTabs.activeTabId) {
      const newIndex = Math.min(index, tabs.length - 1);
      activateTab(tabs[newIndex].id);
    }
    
    updateTabWidths();
  }

  // 刷新标签
  function refreshTab(tabId) {
    const tab = window.tauriTabs.tabs.find(t => t.id === tabId);
    if (!tab) return;
    
    window.tauriTabs.log(`🔄 刷新标签: ${tabId}`);
    tab.iframe.src = tab.iframe.src;
  }

  // 复制标签
  function duplicateTab(tabId) {
    const tab = window.tauriTabs.tabs.find(t => t.id === tabId);
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    
    if (!tab) return;
    
    if (tabs.length >= TAB_CONFIG.maxTabs) {
      alert(`最多只能打开 ${TAB_CONFIG.maxTabs} 个标签`);
      return;
    }
    
    log(`📋 复制标签: ${tabId}, URL: ${tab.url}`);
    
    let currentUrl = tab.url;
    try {
      const iframeWindow = tab.iframe.contentWindow;
      if (iframeWindow && iframeWindow.location && iframeWindow.location.href) {
        currentUrl = iframeWindow.location.href;
        log(`   使用 iframe 当前 URL: ${currentUrl}`);
      }
    } catch (err) {
      log(`   无法获取 iframe 当前 URL，使用原始 URL: ${tab.url}`);
    }
    
    createTab(currentUrl);
  }

  // 在新窗口打开标签
  async function openTabInNewWindow(tabId) {
    const tab = window.tauriTabs.tabs.find(t => t.id === tabId);
    const log = window.tauriTabs.log;
    const invoke = window.tauriTabs.invoke;
    
    if (!tab) return;
    
    log(`🪟 在新窗口打开: ${tab.url}`);
    try {
      await invoke('create_new_window', { 
        currentUrl: tab.url,
        storageData: null
      });
    } catch (err) {
      console.error('Failed to open new window:', err);
    }
  }

  // 关闭左侧标签
  function closeTabsToLeft(tabId) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    const index = tabs.findIndex(t => t.id === tabId);
    
    if (index <= 0) return;
    
    log(`⬅️ 关闭左侧 ${index} 个标签`);
    
    for (let i = index - 1; i >= 0; i--) {
      closeTab(tabs[i].id);
    }
  }

  // 关闭右侧标签
  function closeTabsToRight(tabId) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    const index = tabs.findIndex(t => t.id === tabId);
    
    if (index === -1 || index === tabs.length - 1) return;
    
    const count = tabs.length - index - 1;
    log(`➡️ 关闭右侧 ${count} 个标签`);
    
    for (let i = tabs.length - 1; i > index; i--) {
      closeTab(tabs[i].id);
    }
  }

  // 关闭其他标签
  function closeOtherTabs(tabId) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    const tabsToClose = tabs.filter(t => t.id !== tabId);
    
    log(`🗑️ 关闭其他 ${tabsToClose.length} 个标签`);
    
    tabsToClose.forEach(tab => closeTab(tab.id));
  }

  // 重新排序标签
  function reorderTabs(draggedId, targetId) {
    const tabs = window.tauriTabs.tabs;
    const log = window.tauriTabs.log;
    const draggedIndex = tabs.findIndex(t => t.id === draggedId);
    const targetIndex = tabs.findIndex(t => t.id === targetId);
    
    if (draggedIndex === -1 || targetIndex === -1 || draggedIndex === targetIndex) return;
    
    log(`🔄 标签重新排序: ${draggedId} (索引 ${draggedIndex}) 移动到 ${targetId} (索引 ${targetIndex})`);
    
    // 移动数组中的位置
    const [draggedTab] = tabs.splice(draggedIndex, 1);
    tabs.splice(targetIndex, 0, draggedTab);
    
    // 更新 DOM
    const tabsContainer = document.querySelector('.tauri-tabs-container');
    const newTabBtn = tabsContainer.querySelector('.tauri-new-tab');
    
    // 清空标签容器（保留新建按钮）
    Array.from(tabsContainer.children).forEach(child => {
      if (!child.classList.contains('tauri-new-tab')) {
        child.remove();
      }
    });
    
    // 按新顺序添加标签
    tabs.forEach(tab => {
      tabsContainer.insertBefore(tab.element, newTabBtn);
    });
    
    updateTabWidths();
    log(`✅ 标签重新排序完成`);
  }

  // 更新标签标题
  function updateTabTitle(id, title) {
    const tab = window.tauriTabs.tabs.find(t => t.id === id);
    const log = window.tauriTabs.log;
    
    if (!tab) {
      log(`⚠️  updateTabTitle: 找不到标签 ${id}`);
      return;
    }
    
    if (tab.title === title) return;
    
    tab.title = title;
    const titleSpan = tab.element.querySelector('.tauri-tab-title');
    if (titleSpan) {
      titleSpan.textContent = title;
      titleSpan.title = title;
      log(`✅ 标签标题已更新: ${id} -> ${title}`);
    } else {
      log(`⚠️  找不到标题元素: ${id}`);
    }
    
    if (id === window.tauriTabs.activeTabId) {
      updateMainWindowTitle(title);
    }
  }

  // 更新主窗口标题
  async function updateMainWindowTitle(title) {
    try {
      const invoke = window.tauriTabs.invoke;
      await invoke('set_window_title', { title: `${title} - ${window.tauriTabs.envName || 'Backstage68'}` });
    } catch (err) {
      console.error('Failed to update window title:', err);
    }
  }

  /**
   * 标签页事件模块 - 键盘快捷键、拖拽、右键菜单
   */


  // 初始化事件监听
  function initTabEvents() {
    setupKeyboardShortcuts();
    setupDragEvents();
    window.tauriTabs.showContextMenu = showTabContextMenu;
  }

  // 键盘快捷键
  function setupKeyboardShortcuts() {
    if (window.self !== window.top) return;
    
    document.addEventListener('keydown', (e) => {
      const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
      const isCtrlOrCmd = isMac ? e.metaKey : e.ctrlKey;
      
      if (!isCtrlOrCmd) return;
      if (!window.tauriTabs || !window.tauriTabs.tabs) return;
      
      // Cmd+T: 新建标签
      if (e.key === 't') {
        e.preventDefault();
        e.stopPropagation();
        const activeTab = window.tauriTabs.tabs.find(t => t.id === window.tauriTabs.activeTabId);
        const currentUrl = activeTab ? activeTab.url : window.location.href;
        createTab(currentUrl);
      }
      
      // Cmd+W: 关闭当前标签
      else if (e.key === 'w') {
        if (window.tauriTabs.tabs.length > 1 && window.tauriTabs.activeTabId) {
          e.preventDefault();
          e.stopPropagation();
          closeTab(window.tauriTabs.activeTabId);
        }
      }
      
      // Cmd+Shift+N: 新窗口
      else if (e.key === 'N' && e.shiftKey) {
        e.preventDefault();
        e.stopPropagation();
        const activeTab = window.tauriTabs.tabs.find(t => t.id === window.tauriTabs.activeTabId);
        const currentUrl = activeTab ? activeTab.url : window.location.href;
        if (window.tauriOpenNewWindow) {
          window.tauriOpenNewWindow(currentUrl);
        }
      }
      
      // Cmd+Shift+A: 搜索标签
      else if (e.key === 'A' && e.shiftKey) {
        e.preventDefault();
        e.stopPropagation();
        if (window.tauriTabs.showSearch) {
          window.tauriTabs.showSearch();
        }
      }
      
      // Cmd+数字键: 快速切换标签 (1-9)
      else if (e.key >= '1' && e.key <= '9') {
        e.preventDefault();
        e.stopPropagation();
        const index = parseInt(e.key) - 1;
        const tabs = window.tauriTabs.tabs;
        if (index < tabs.length) {
          activateTab(tabs[index].id);
        }
      }
    }, true);
  }

  // 拖拽事件
  function setupDragEvents() {
    const log = window.tauriTabs.log;
    
    window.tauriTabs.dragEvents = {
      dragStart: (e, id, tab) => {
        e.dataTransfer.effectAllowed = 'move';
        e.dataTransfer.setData('text/plain', id);
        tab.style.opacity = '0.5';
        tab.classList.add('dragging');
        log(`🖱️ 开始拖动标签: ${id}`);
      },
      
      dragEnd: (e, id, tab) => {
        tab.style.opacity = '1';
        tab.classList.remove('dragging');
        document.querySelectorAll('.tauri-tab.drag-over').forEach(t => {
          t.classList.remove('drag-over');
        });
        log(`🖱️ 结束拖动标签: ${id}`);
      },
      
      dragOver: (e, tab) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = 'move';
        if (!tab.classList.contains('dragging')) {
          tab.classList.add('drag-over');
        }
      },
      
      dragLeave: (e, tab) => {
        tab.classList.remove('drag-over');
      },
      
      drop: (e, id, tab) => {
        e.preventDefault();
        e.stopPropagation();
        tab.classList.remove('drag-over');
        
        const draggedId = e.dataTransfer.getData('text/plain');
        if (draggedId && draggedId !== id) {
          log(`📍 放置标签: ${draggedId} -> ${id}`);
          reorderTabs(draggedId, id);
        }
      }
    };
  }

  // 显示右键菜单
  function showTabContextMenu(tabId, x, y) {
    // 移除旧菜单
    const oldMenu = document.querySelector('.tauri-tab-context-menu');
    if (oldMenu) oldMenu.remove();
    
    const menu = document.createElement('div');
    menu.className = 'tauri-tab-context-menu';
    menu.style.cssText = `
    position: fixed;
    left: ${x}px;
    top: ${y}px;
    background: rgba(30, 30, 30, 0.95);
    backdrop-filter: blur(20px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 8px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
    padding: 6px;
    z-index: 9999999;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 13px;
    min-width: 180px;
    color: white;
  `;
    
    const menuItems = [
      { text: '🔄 刷新', action: () => refreshTab(tabId) },
      { text: '📋 复制标签', action: () => duplicateTab(tabId) },
      { text: '🪟 在新窗口打开', action: () => openTabInNewWindow(tabId) },
      { divider: true },
      { text: '❌ 关闭', action: () => closeTab(tabId) },
      { text: '⬅️ 关闭左侧标签', action: () => closeTabsToLeft(tabId) },
      { text: '➡️ 关闭右侧标签', action: () => closeTabsToRight(tabId) },
      { text: '🗑️ 关闭其他标签', action: () => closeOtherTabs(tabId) }
    ];
    
    menuItems.forEach(item => {
      if (item.divider) {
        const divider = document.createElement('div');
        divider.style.cssText = `
        height: 1px;
        background: rgba(255, 255, 255, 0.1);
        margin: 4px 0;
      `;
        menu.appendChild(divider);
      } else {
        const menuItem = document.createElement('div');
        menuItem.textContent = item.text;
        menuItem.style.cssText = `
        padding: 8px 12px;
        cursor: pointer;
        border-radius: 4px;
        transition: background 0.15s;
      `;
        menuItem.addEventListener('mouseenter', () => {
          menuItem.style.background = 'rgba(255, 255, 255, 0.1)';
        });
        menuItem.addEventListener('mouseleave', () => {
          menuItem.style.background = 'transparent';
        });
        menuItem.addEventListener('click', () => {
          item.action();
          menu.remove();
        });
        menu.appendChild(menuItem);
      }
    });
    
    document.body.appendChild(menu);
    
    // 点击其他地方关闭菜单
    setTimeout(() => {
      const closeMenu = (e) => {
        if (!menu.contains(e.target)) {
          menu.remove();
          document.removeEventListener('click', closeMenu, true);
          document.removeEventListener('contextmenu', closeMenu, true);
          
          // 移除所有 iframe 的监听器
          window.tauriTabs.tabs.forEach(tab => {
            try {
              const iframeDoc = tab.iframe.contentDocument;
              if (iframeDoc) {
                iframeDoc.removeEventListener('click', closeMenu, true);
                iframeDoc.removeEventListener('contextmenu', closeMenu, true);
              }
            } catch (err) {
              // 忽略跨域错误
            }
          });
        }
      };
      
      document.addEventListener('click', closeMenu, true);
      document.addEventListener('contextmenu', closeMenu, true);
      
      // 在所有 iframe 添加监听器
      window.tauriTabs.tabs.forEach(tab => {
        try {
          const iframeDoc = tab.iframe.contentDocument;
          if (iframeDoc) {
            iframeDoc.addEventListener('click', closeMenu, true);
            iframeDoc.addEventListener('contextmenu', closeMenu, true);
          }
        } catch (err) {
          // 忽略跨域错误
        }
      });
    }, 100);
  }

  // 添加上下文菜单样式
  const contextMenuStyle = document.createElement('style');
  contextMenuStyle.textContent = `
  .tauri-tab-context-menu {
    animation: menuFadeIn 0.15s ease-out;
  }
  @keyframes menuFadeIn {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
`;
  document.head.appendChild(contextMenuStyle);

  /**
   * 标签页搜索模块
   */


  // 显示标签搜索对话框
  function showTabSearch() {
    const log = window.tauriTabs.log;
    log('🔍 打开标签搜索');
    
    // 创建遮罩层
    const overlay = document.createElement('div');
    overlay.className = 'tauri-tab-search-overlay';
    
    // 创建对话框
    const dialog = document.createElement('div');
    dialog.className = 'tauri-tab-search-dialog';
    
    // 搜索输入框
    const input = document.createElement('input');
    input.type = 'text';
    input.className = 'tauri-tab-search-input';
    input.placeholder = '搜索标签标题';
    
    // 结果容器
    const results = document.createElement('div');
    results.className = 'tauri-tab-search-results';
    
    dialog.appendChild(input);
    dialog.appendChild(results);
    overlay.appendChild(dialog);
    document.body.appendChild(overlay);
    
    let selectedIndex = 0;
    
    // 渲染搜索结果
    function renderResults(query = '') {
      const tabs = window.tauriTabs.tabs;
      const filtered = query.trim() === '' ? tabs : tabs.filter(tab => {
        const title = (tab.title || '').toLowerCase();
        const q = query.toLowerCase();
        return title.includes(q); // 只搜索标题
      });
      
      results.innerHTML = '';
      
      if (filtered.length === 0) {
        const empty = document.createElement('div');
        empty.className = 'tauri-tab-search-empty';
        empty.textContent = '没有找到匹配的标签';
        results.appendChild(empty);
        return;
      }
      
      filtered.forEach((tab, index) => {
        const item = document.createElement('div');
        item.className = 'tauri-tab-search-item';
        if (index === selectedIndex) {
          item.classList.add('selected');
        }
        
        const icon = document.createElement('div');
        icon.className = 'tauri-tab-search-item-icon';
        icon.textContent = '📄';
        
        const content = document.createElement('div');
        content.className = 'tauri-tab-search-item-content';
        
        const titleEl = document.createElement('div');
        titleEl.className = 'tauri-tab-search-item-title';
        titleEl.textContent = tab.title || 'Untitled';
        
        content.appendChild(titleEl);
        item.appendChild(icon);
        item.appendChild(content);
        
        item.addEventListener('click', () => {
          activateTab(tab.id);
          closeSearch();
        });
        
        results.appendChild(item);
      });
      
      selectedIndex = Math.min(selectedIndex, filtered.length - 1);
    }
    
    // 关闭搜索
    function closeSearch() {
      overlay.remove();
      log('🔍 关闭标签搜索');
    }
    
    // 输入事件
    input.addEventListener('input', () => {
      selectedIndex = 0;
      renderResults(input.value);
    });
    
    // 键盘事件
    input.addEventListener('keydown', (e) => {
      const items = results.querySelectorAll('.tauri-tab-search-item');
      
      if (e.key === 'Escape') {
        e.preventDefault();
        closeSearch();
      } else if (e.key === 'ArrowDown') {
        e.preventDefault();
        selectedIndex = Math.min(selectedIndex + 1, items.length - 1);
        renderResults(input.value);
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        selectedIndex = Math.max(selectedIndex - 1, 0);
        renderResults(input.value);
      } else if (e.key === 'Enter') {
        e.preventDefault();
        if (items[selectedIndex]) {
          items[selectedIndex].click();
        }
      }
    });
    
    // 点击遮罩关闭
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) {
        closeSearch();
      }
    });
    
    // 初始渲染
    renderResults();
    
    // 自动聚焦
    setTimeout(() => input.focus(), 100);
  }

  // 添加搜索样式
  const searchStyle = document.createElement('style');
  searchStyle.textContent = `
  .tauri-tab-search-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,0.7);
    z-index: 10000000;
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 100px;
    animation: overlayFadeIn 0.2s ease-out;
  }
  @keyframes overlayFadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }
  .tauri-tab-search-dialog {
    background: #2c2c2c;
    border-radius: 12px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.8);
    border: 1px solid #444;
    width: 600px;
    max-width: 90vw;
    max-height: 500px;
    display: flex;
    flex-direction: column;
    animation: dialogSlideIn 0.3s ease-out;
    overflow: hidden;
  }
  @keyframes dialogSlideIn {
    from {
      opacity: 0;
      transform: translateY(-20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  .tauri-tab-search-input {
    width: 100%;
    padding: 16px 20px;
    background: #1e1e1e;
    border: none;
    border-bottom: 1px solid #444;
    color: #e0e0e0;
    font-size: 16px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    outline: none;
    border-radius: 12px 12px 0 0;
    box-sizing: border-box;
  }
  .tauri-tab-search-input:focus {
    background: #252525;
    border-bottom-color: #0066cc;
  }
  .tauri-tab-search-input::placeholder {
    color: #888;
  }
  .tauri-tab-search-results {
    flex: 1;
    overflow-y: auto;
    padding: 8px 0;
    min-height: 100px;
  }
  .tauri-tab-search-results::-webkit-scrollbar {
    width: 8px;
  }
  .tauri-tab-search-results::-webkit-scrollbar-track {
    background: #2c2c2c;
  }
  .tauri-tab-search-results::-webkit-scrollbar-thumb {
    background: #555;
    border-radius: 4px;
  }
  .tauri-tab-search-results::-webkit-scrollbar-thumb:hover {
    background: #666;
  }
  .tauri-tab-search-item {
    padding: 12px 20px;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 12px;
    transition: background 0.15s;
  }
  .tauri-tab-search-item:hover {
    background: rgba(255,255,255,0.1);
  }
  .tauri-tab-search-item.selected {
    background: rgba(0,102,204,0.3);
  }
  .tauri-tab-search-item-icon {
    font-size: 20px;
    flex-shrink: 0;
  }
  .tauri-tab-search-item-content {
    flex: 1;
    min-width: 0;
  }
  .tauri-tab-search-item-title {
    color: #e0e0e0;
    font-size: 14px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .tauri-tab-search-empty {
    padding: 40px 20px;
    text-align: center;
    color: #888;
    font-size: 14px;
  }
`;
  document.head.appendChild(searchStyle);

  /**
   * 标签页管理模块
   */


  function initTabs(log, invoke) {
    // 检查是否在 iframe 内部
    if (window.self !== window.top) {
      log("⚠️  在 iframe 内，跳过标签页初始化");
      return;
    }
    
    // 检查是否已经初始化过
    if (window.__TAURI_TABS_INITIALIZED__) {
      log("⚠️  标签页系统已初始化，跳过");
      return;
    }
    
    // 等待 DOM 加载完成
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => initTabs(log, invoke));
      return;
    }
    
    log("🏷️ 初始化标签页模块...");
    
    // 标记已初始化
    window.__TAURI_TABS_INITIALIZED__ = true;
    
    // 获取环境名称
    let envName = 'Backstage68';
    (async function() {
      try {
        const envInfo = await invoke('get_env_info');
        const match = envInfo.match(/当前环境: (.+?) \(/);
        if (match) {
          envName = match[1];
        }
      } catch (err) {
        // 使用默认值
      }
    })();

    // 创建标签管理器
    window.tauriTabs = {
      tabs: [],
      activeTabId: null,
      nextId: 0,
      currentZoom: 1.0,
      envName,
      log,
      invoke
    };

    // 创建标签栏
    const { tabsContainer, controlsContainer } = createTabBar();
    
    // 添加新建按钮
    const newTabBtn = document.createElement('div');
    newTabBtn.className = 'tauri-new-tab';
    newTabBtn.innerHTML = '+';
    newTabBtn.title = '新建标签 (Cmd+T)';
    newTabBtn.onclick = (e) => {
      e.preventDefault();
      e.stopPropagation();
      const activeTab = window.tauriTabs.tabs.find(t => t.id === window.tauriTabs.activeTabId);
      const currentUrl = activeTab ? activeTab.url : window.location.href;
      createTab(currentUrl);
    };
    tabsContainer.appendChild(newTabBtn);
    
    // 添加搜索按钮
    const searchBtn = document.createElement('div');
    searchBtn.className = 'tauri-search-tab';
    searchBtn.innerHTML = '🔍';
    searchBtn.title = '搜索标签 (Cmd+Shift+A)';
    searchBtn.onclick = (e) => {
      e.preventDefault();
      e.stopPropagation();
      showTabSearch();
    };
    controlsContainer.appendChild(searchBtn);

    // 初始化事件监听
    initTabEvents();

    // 创建首个标签
    const initialUrl = window.location.href;
    createTab(initialUrl);
    
    // 隐藏原始 body 内容
    Array.from(document.body.children).forEach(child => {
      if (child.id !== 'tauri-tab-bar' && 
          !child.classList.contains('tauri-iframe-container') &&
          !child.id?.includes('zoom')) {
        child.style.display = 'none';
      }
    });

    // 窗口大小变化时更新标签宽度
    let resizeTimer;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        updateTabWidths();
        log('🔄 窗口大小变化，重新计算标签宽度');
      }, 200);
    });

    // 暴露 API
    window.tauriTabs.createTab = createTab;
    window.tauriTabs.closeTab = closeTab;
    window.tauriTabs.activateTab = activateTab;
    window.tauriTabs.duplicateTab = duplicateTab;
    window.tauriTabs.reorderTabs = reorderTabs;
    window.tauriTabs.showSearch = showTabSearch;
    window.tauriTabs.updateTabWidths = updateTabWidths;

    log("✅ 标签页模块已启用");
    console.log("🎉 标签页功能已启用:");
    console.log("  ╔════════════════════════════════════╗");
    console.log("  ║  快捷键                            ║");
    console.log("  ╠════════════════════════════════════╣");
    console.log("  ║  Cmd+T          新建标签           ║");
    console.log("  ║  Cmd+W          关闭当前标签       ║");
    console.log("  ║  Cmd+Shift+A    搜索标签           ║");
    console.log("  ║  Cmd+Shift+N    新窗口（多窗口）   ║");
    console.log("  ║  Cmd+1~9        切换到第 N 个标签  ║");
    console.log("  ╠════════════════════════════════════╣");
    console.log("  ║  鼠标操作                          ║");
    console.log("  ╠════════════════════════════════════╣");
    console.log("  ║  拖动标签        重新排序          ║");
    console.log("  ║  右键标签        显示菜单          ║");
    console.log("  ║  点击 🔍        搜索标签           ║");
    console.log("  ║  点击 +          新建标签          ║");
    console.log("  ╚════════════════════════════════════╝");
    console.log(`  最多支持 ${TAB_CONFIG.maxTabs} 个标签，动态宽度，拖动排序，搜索功能`);
  }

  /**
   * Tauri 注入脚本 - 重构版本
   * 
   * 模块化架构：
   * ├── logger.js - 日志工具
   * ├── utils/
   * │   ├── dom.js - DOM 工具函数
   * │   └── storage.js - 存储工具
   * ├── proxy.js - HTTP 代理拦截 (Fetch + XMLHttpRequest)
   * ├── zoom.js - 页面缩放控制
   * ├── window.js - 多窗口支持和标题同步
   * └── tabs/
   *     ├── manager.js - 标签页管理器（主入口）
   *     ├── ui.js - 标签栏 UI 和样式
   *     ├── operations.js - 标签 CRUD 操作
   *     ├── events.js - 键盘快捷键和拖拽
   *     └── search.js - 标签搜索功能
   * 
   * 从 2089 行单文件重构为 11 个模块，平均每个模块 ~170 行
   */


  (function() {
    const log = initLogger();
    log("🚀 Tauri 注入脚本启动（重构版）");

    // 检查是否在 iframe 内
    if (isInIframe()) {
      log("⚠️  检测到在 iframe 内，跳过初始化");
      return;
    }

    // 检查 Tauri API
    if (!window.__TAURI__ || !window.__TAURI__.core || !window.__TAURI__.core.invoke) {
      console.error("❌ Tauri API 不可用！代理将无法工作");
      return;
    }

    const invoke = window.__TAURI__.core.invoke;
    log("✅ Tauri API 准备就绪");

    // 初始化各模块
    try {
      // 1. 代理拦截（拦截所有 /base_api/ 请求，添加安全头）
      initProxy(log, invoke);

      // 2. 页面缩放（Cmd +/-/0，滚轮缩放）
      initZoom(log);

      // 3. 多窗口支持（Cmd+Shift+N，共享登录状态）
      initWindow(log, invoke);

      // 4. 标签页系统（浏览器风格标签页，支持 20 个标签）
      initTabs(log, invoke);

      log("🎉 所有模块初始化完成");
    } catch (err) {
      console.error("❌ 模块初始化失败:", err);
    }
  })();

})();
//# sourceMappingURL=inject.js.map
